const tags = {
    episode: 'エピソード',
    goods: 'グッズ',
    update: 'アップデート',
    campaign: 'キャンペーン',
    other: 'その他',
};

const news = [
    {
        date: '2023.5.4',
        head: 'お酒一覧ページに「面向未来」を追加しました',
        url: '/liquorlist#60',
        tag: tags.update,
    },
    {
        date: '2023.4.25',
        head: '第39話が更新されました！',
        url: 'https://mangacross.jp/comics/kamiinabotan/42',
        tag: tags.episode,
    },
    {
        date: '2023.4.20',
        head: 'PIXIV FANBOXで「【上伊那ぼたん】第7話ネーム公開」がアップされました',
        url: 'https://tonarinohey.fanbox.cc/posts/5770727',
        tag: tags.goods,
    },
    {
        date: '2023.3.28',
        head: '第38話が更新されました！',
        url: 'https://mangacross.jp/comics/kamiinabotan/41',
        tag: tags.episode,
    },
    {
        date: '2023.3.14',
        head: 'PIXIV FANBOXで「【上伊那ぼたん】第6話ネーム公開」がアップされました',
        url: 'https://tonarinohey.fanbox.cc/posts/5494118',
        tag: tags.goods,
    },
    {
        date: '2023.3.5',
        head: 'お酒一覧ページに「越の鶴 純米吟醸」など4種を追加しました',
        url: '/liquorlist',
        tag: tags.update,
    },
    {
        date: '2023.2.28',
        head: '第37話が更新されました！',
        url: 'https://mangacross.jp/comics/kamiinabotan/40',
        tag: tags.episode,
    },
    {
        date: '2023.2.25',
        head: 'PIXIV FANBOXで「【上伊那ぼたん】第5話ネーム公開」がアップされました',
        url: 'https://tonarinohey.fanbox.cc/posts/5367995',
        tag: tags.goods,
    },
    {
        date: '2023.2.4',
        head: 'PIXIV FANBOXで「【上伊那ぼたん】第4話ネーム公開」がアップされました',
        url: 'https://tonarinohey.fanbox.cc/posts/5236414',
        tag: tags.goods,
    },
    {
        date: '2023.2.2',
        head: 'お酒一覧ページに「秩父梅ざけカップ」を追加しました',
        url: '/liquorlist',
        tag: tags.update,
    },
    {
        date: '2023.1.31',
        head: '第36話が更新されました！',
        url: 'https://mangacross.jp/comics/kamiinabotan/39',
        tag: tags.episode,
    },
    {
        date: '2022.12.16',
        head: 'PIXIV FANBOXで「【上伊那ぼたん】第3話ネーム公開」がアップされました',
        url: 'https://tonarinohey.fanbox.cc/posts/4937227',
        tag: tags.goods,
    },
    {
        date: '2022.12.10',
        head: 'お酒一覧ページに「みんなの飲んだよカウンター」を追加しました！',
        url: '/liquorlist',
        tag: tags.update,
    },

    {
        date: '2022.11.29',
        head: '第35話が更新されました！',
        url: 'https://mangacross.jp/comics/kamiinabotan/38',
        tag: tags.episode,
    },
    {
        date: '2022.11.23',
        head: '繊維新聞に塀先生のインタビューが掲載されました！',
        url: 'https://senken.co.jp/posts/manga-fashion',
        tag: tags.other,
    },
    {
        date: '2022.10.26',
        head: 'PIXIV FANBOXで「【上伊那ぼたん】第2話ネーム公開」がアップされました',
        url: 'https://tonarinohey.fanbox.cc/posts/4657062',
        tag: tags.goods,
    },
    {
        date: '2022.10.25',
        head: '第34話が更新されました！',
        url: 'https://mangacross.jp/comics/kamiinabotan/37',
        tag: tags.episode,
    },
    {
        date: '2022.10.26',
        head: 'PIXIV FANBOXで「【上伊那ぼたん】7話のお酒などを振り返る」がアップされました',
        url: 'https://tonarinohey.fanbox.cc/posts/4654589',
        tag: tags.goods,
    },
    {
        date: '2022.10.13',
        head: 'PIXIV FANBOXで「【上伊那ぼたん】第1話ネーム公開」がアップされました',
        url: 'https://tonarinohey.fanbox.cc/posts/4590515',
        tag: tags.goods,
    },
    {
        date: '2022.10.12',
        head: 'PIXIV FANBOXで「【上伊那ぼたん】6話のお酒などを振り返る」がアップされました',
        url: 'https://tonarinohey.fanbox.cc/posts/4576240',
        tag: tags.goods,
    },
    {
        date: '2022.10.06',
        head: 'PIXIV FANBOXで「【上伊那ぼたん】5話のお酒などを振り返る」がアップされました',
        url: 'https://tonarinohey.fanbox.cc/posts/4556544',
        tag: tags.goods,
    },
    {
        date: '2022.10.04',
        head: 'PIXIV FANBOXで「【上伊那ぼたん】4話のお酒などを振り返る」がアップされました',
        url: 'https://tonarinohey.fanbox.cc/posts/4542199',
        tag: tags.goods,
    },
    {
        date: '2022.10.04',
        head: 'PIXIV FANBOXで「【上伊那ぼたん】単行本1巻カバー案ラフ」がアップされました',
        url: 'https://tonarinohey.fanbox.cc/posts/4547698',
        tag: tags.goods,
    },
    {
        date: '2022.10.01',
        head: 'PIXIV FANBOXで「【上伊那ぼたん】3話のお酒を振り返る」がアップされました',
        url: 'https://tonarinohey.fanbox.cc/posts/4527795',
        tag: tags.goods,
    },
    {
        date: '2022.09.29',
        head: 'PIXIV FANBOXで「【上伊那ぼたん】2話のお酒を振り返る」がアップされました',
        url: 'https://tonarinohey.fanbox.cc/posts/4508400',
        tag: tags.goods,
    },
    {
        date: '2022.09.27',
        head: 'PIXIV FANBOXで「【上伊那ぼたん】1話のお酒を振り返る」がアップされました',
        url: 'https://tonarinohey.fanbox.cc/posts/4504510',
        tag: tags.goods,
    },
    {
        date: '2022.09.27',
        head: '第33話が更新されました！',
        url: 'https://mangacross.jp/comics/kamiinabotan/36',
        tag: tags.episode,
    },
    {
        date: '2022.09.20',
        head: '作者の塀先生がPIXIV FANBOXをスタートしました！',
        url: 'https://tonarinohey.fanbox.cc/posts/4472682?utm_campaign=post_page&utm_medium=share&utm_source=twitter',
        tag: tags.goods,
    },
    {
        date: '2022.08.30',
        head: '第32話が更新されました！',
        url: 'https://mangacross.jp/comics/kamiinabotan/35',
        tag: tags.episode,
    },
    {
        date: '2022.08.27',
        head: '「キャラクター一覧」を更新しました',
        url: 'https://yuriyoi.site/characters',
        tag: tags.update,
    },
    {
        date: '2022.08.03',
        head: '「ファッションで見る」の香水を更新しました',
        url: 'https://yuriyoi.site/clothes',
        tag: tags.update,
    },
    {
        date: '2022.07.29',
        head: '「ファッションで見る」に香水の項目を追加しました',
        url: 'https://yuriyoi.site/clothes',
        tag: tags.update,
    },
    {
        date: '2022.07.26',
        head: '第31話が更新されました！',
        url: 'https://mangacross.jp/comics/kamiinabotan/34',
        tag: tags.episode,
    },
    {
        date: '2022.07.06',
        head: '最新話リンクの更新・TOPページのデザイン微修正しました',
        url: '/',
        tag: tags.update,
    },
    {
        date: '2022.06.02',
        head: '「ファッションで見る」ページを更新しました',
        url: 'https://yuriyoi.site/clothes',
        tag: tags.update,
    },
    {
        date: '2022.05.28',
        head: 'Kindle版第1巻が半額セール中！',
        url: 'https://amzn.to/3z8v88H',
        tag: tags.campaign,
    },
    {
        date: '2022.05.18',
        head: '次に来るマンガ大賞2022のエントリーが開始されました',
        url: 'https://tsugimanga.jp/',
        tag: tags.campaign,
    },
    {
        date: '2022.05.11',
        head: '単行本題1巻がKindleで5月13日(金)23時59分まで無料公開中！',
        url: 'https://amzn.to/3FwiYb1',
        tag: tags.goods,
    },
    {
        date: '2022.05.06',
        head: '上伊那ぼたんクイズのページを追加しました！',
        url: 'https://yuriyoi.site/quiz',
        tag: tags.update,
    },
    {
        date: '2022.04.28',
        head: '単行本題1巻の重版が決定しました！',
        url: 'https://amzn.to/3rYpS2Y',
        tag: tags.goods,
    },
    {
        date: '2022.04.26',
        head: '第29話が更新されました！',
        url: 'https://mangacross.jp/comics/kamiinabotan/32',
        tag: tags.episode,
    },
    {
        date: '2022.03.29',
        head: '第28話が更新されました！',
        url: 'https://mangacross.jp/comics/kamiinabotan/31',
        tag: tags.episode,
    },
    {
        date: '2022.03.17',
        head: '単行本題3巻がされました！',
        url: 'https://amzn.to/3JOSmSX',
        tag: tags.goods,
    },
    {
        date: '2022.03.05',
        head: '上伊那ぼたんのLINEスタンプがリリースされました！',
        url: 'https://store.line.me/stickershop/product/18651031/',
        tag: tags.goods,
    },
];

export default news;
